/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AgentSummary {
  'resolutionRate' : number,
  'displayName' : string,
  'agentId' : UserId,
  'resolvedTicketCount' : bigint,
  'assignedTicketCount' : bigint,
}
export type AppRole = { 'admin' : null } |
  { 'l2_resolver' : null } |
  { 'l1_help_desk' : null } |
  { 'employee' : null };
export interface Attachment {
  'id' : AttachmentId,
  'mimeType' : string,
  'fileName' : string,
  'storageKey' : string,
  'sizeBytes' : bigint,
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
}
export type AttachmentId = bigint;
export type AuditAction = { 'priorityUpdated' : null } |
  { 'ticketAssigned' : null } |
  { 'userDeactivated' : null } |
  { 'categoryUpdated' : null } |
  { 'userReactivated' : null } |
  { 'settingsUpdated' : null } |
  { 'ticketStatusChanged' : null } |
  { 'ticketCreated' : null } |
  { 'ticketClosed' : null } |
  { 'roleChanged' : null } |
  { 'categoryCreated' : null };
export type AuditLogId = bigint;
export interface AuditLogQuery {
  'toTimestamp' : [] | [Timestamp],
  'action' : [] | [AuditAction],
  'fromTimestamp' : [] | [Timestamp],
  'page' : PageRequest,
  'actorId' : [] | [UserId],
}
export interface AuditLogView {
  'id' : AuditLogId,
  'action' : AuditAction,
  'actorId' : UserId,
  'detail' : string,
  'timestamp' : Timestamp,
  'targetEntity' : string,
}
export interface CategoryCreateInput { 'name' : string, 'description' : string }
export type CategoryId = bigint;
export interface CategoryUpdateInput {
  'id' : CategoryId,
  'name' : [] | [string],
  'description' : [] | [string],
  'isActive' : [] | [boolean],
}
export interface CategoryView {
  'id' : CategoryId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
}
export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface KnowledgeArticleCreateInput {
  'categoryId' : [] | [CategoryId],
  'title' : string,
  'content' : string,
}
export type KnowledgeArticleId = bigint;
export interface KnowledgeArticleUpdateInput {
  'id' : KnowledgeArticleId,
  'categoryId' : [] | [[] | [CategoryId]],
  'title' : [] | [string],
  'content' : [] | [string],
}
export interface KnowledgeArticleView {
  'id' : KnowledgeArticleId,
  'categoryId' : [] | [CategoryId],
  'title' : string,
  'content' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export type MessageId = bigint;
export interface NavItem {
  'name' : string,
  'badgeCount' : [] | [bigint],
  'route' : string,
}
export type NotificationId = bigint;
export type NotificationType = { 'ticketReply' : null } |
  { 'ticketUpdated' : null } |
  { 'ticketAssigned' : null } |
  { 'ticketClosed' : null } |
  { 'roleChanged' : null };
export interface NotificationView {
  'id' : NotificationId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'recipient' : UserId,
  'isRead' : boolean,
  'message' : string,
  'linkTicketId' : [] | [TicketId],
}
export interface PageRequest { 'page' : bigint, 'pageSize' : bigint }
export interface PriorityCreateInput {
  'name' : string,
  'level' : bigint,
  'slaTargetNs' : bigint,
}
export type PriorityId = bigint;
export interface PriorityUpdateInput {
  'id' : PriorityId,
  'name' : [] | [string],
  'isActive' : [] | [boolean],
  'level' : [] | [bigint],
  'slaTargetNs' : [] | [bigint],
}
export interface PriorityView {
  'id' : PriorityId,
  'name' : string,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'level' : bigint,
  'slaTargetNs' : bigint,
}
export type ResolverQueue = { 'l1Default' : null } |
  { 'l2Default' : null };
export type ResolverTier = { 'l1' : null } |
  { 'l2' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface RoleDashboard {
  'kpis' : Array<RoleKPI>,
  'role' : AppRole,
  'queue' : ResolverQueue,
  'queueTicketCount' : bigint,
}
export interface RoleKPI { 'value' : bigint, 'name' : string }
export interface RoleNavigation { 'role' : AppRole, 'items' : Array<NavItem> }
export type SortOrder = { 'asc' : null } |
  { 'desc' : null };
export interface SystemSettingsUpdateInput {
  'organizationName' : [] | [string],
  'aiFeaturesEnabled' : [] | [boolean],
}
export interface SystemSettingsView {
  'organizationName' : string,
  'updatedAt' : Timestamp,
  'aiFeaturesEnabled' : boolean,
}
export interface TicketAnalytics {
  'createdOverTime' : Array<[Timestamp, bigint]>,
  'totalTickets' : bigint,
  'byStatus' : Array<[TicketStatus, bigint]>,
  'byCategory' : Array<[CategoryId, bigint]>,
  'byPriority' : Array<[PriorityId, bigint]>,
}
export interface TicketCreateInput {
  'categoryId' : CategoryId,
  'title' : string,
  'description' : string,
  'priorityId' : PriorityId,
  'attachments' : Array<Attachment>,
}
export type TicketId = bigint;
export interface TicketMessage {
  'id' : MessageId,
  'body' : string,
  'createdAt' : Timestamp,
  'authorRole' : AppRole,
  'ticketId' : TicketId,
  'author' : UserId,
  'isInternal' : boolean,
}
export interface TicketQuery {
  'categoryId' : [] | [CategoryId],
  'status' : [] | [TicketStatus],
  'creator' : [] | [UserId],
  'sortBy' : [] | [
    { 'createdAt' : null } |
      { 'updatedAt' : null } |
      { 'priority' : null }
  ],
  'sortOrder' : [] | [SortOrder],
  'assignedAgent' : [] | [UserId],
  'page' : PageRequest,
  'search' : [] | [string],
  'priorityId' : [] | [PriorityId],
}
export interface TicketSLAStatus {
  'status' : TicketStatus,
  'title' : string,
  'isAtRisk' : boolean,
  'slaDeadline' : Timestamp,
  'isBreached' : boolean,
  'timeRemainingNs' : bigint,
  'ticketId' : TicketId,
  'priorityId' : PriorityId,
}
export type TicketStatus = { 'resolved' : null } |
  { 'closed' : null } |
  { 'pending' : null } |
  { 'in_progress' : null } |
  { 'open' : null };
export interface TicketUpdateInput {
  'status' : [] | [TicketStatus],
  'assignedAgent' : [] | [UserId],
  'resolutionSummary' : [] | [string],
  'ticketId' : TicketId,
}
export interface TicketView {
  'id' : TicketId,
  'categoryId' : CategoryId,
  'status' : TicketStatus,
  'predictedCategory' : [] | [CategoryId],
  'title' : string,
  'creator' : UserId,
  'predictedPriority' : [] | [PriorityId],
  'slaDeadline' : Timestamp,
  'assignedAgent' : [] | [UserId],
  'suggestedSolution' : [] | [string],
  'createdAt' : Timestamp,
  'description' : string,
  'duplicateOf' : [] | [TicketId],
  'updatedAt' : Timestamp,
  'closedAt' : [] | [Timestamp],
  'priorityId' : PriorityId,
  'attachments' : Array<Attachment>,
}
export type Timestamp = bigint;
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserView {
  'id' : UserId,
  'lastSeenAt' : [] | [Timestamp],
  'displayName' : string,
  'createdAt' : Timestamp,
  'role' : AppRole,
  'isActive' : boolean,
  'email' : [] | [string],
}
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[UserId, AppRole], UserView>,
  'closeTicket' : ActorMethod<[TicketId, string], TicketView>,
  'countUnreadNotifications' : ActorMethod<[], bigint>,
  'createCategory' : ActorMethod<[CategoryCreateInput], CategoryView>,
  'createKnowledgeArticle' : ActorMethod<
    [KnowledgeArticleCreateInput],
    KnowledgeArticleView
  >,
  'createPriority' : ActorMethod<[PriorityCreateInput], PriorityView>,
  'createTicket' : ActorMethod<[TicketCreateInput], TicketView>,
  'deactivateUser' : ActorMethod<[UserId], UserView>,
  'escalateTicket' : ActorMethod<[TicketId, string], TicketView>,
  'execute' : ActorMethod<[string], Result>,
  'getCallerAppRole' : ActorMethod<[], [] | [AppRole]>,
  'getCallerResolverTier' : ActorMethod<[], [] | [ResolverTier]>,
  'getCallerUser' : ActorMethod<[], [] | [UserView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategory' : ActorMethod<[CategoryId], [] | [CategoryView]>,
  'getKnowledgeArticle' : ActorMethod<
    [KnowledgeArticleId],
    [] | [KnowledgeArticleView]
  >,
  'getMyQueueTickets' : ActorMethod<[], Array<TicketView>>,
  'getMyRoleDashboard' : ActorMethod<[], RoleDashboard>,
  'getMyRoleNavigation' : ActorMethod<[], RoleNavigation>,
  'getPriority' : ActorMethod<[PriorityId], [] | [PriorityView]>,
  'getSLAStatuses' : ActorMethod<[], Array<TicketSLAStatus>>,
  'getSystemSettings' : ActorMethod<[], SystemSettingsView>,
  'getTicket' : ActorMethod<[TicketId], [] | [TicketView]>,
  'getTicketAnalytics' : ActorMethod<[], TicketAnalytics>,
  'getUser' : ActorMethod<[UserId], [] | [UserView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAgents' : ActorMethod<[], Array<AgentSummary>>,
  'listAgentsByTier' : ActorMethod<[[] | [ResolverTier]], Array<AgentSummary>>,
  'listAllTickets' : ActorMethod<[TicketQuery], Array<TicketView>>,
  'listAuditLogs' : ActorMethod<[AuditLogQuery], Array<AuditLogView>>,
  'listCategories' : ActorMethod<[boolean], Array<CategoryView>>,
  'listKnowledgeArticles' : ActorMethod<[], Array<KnowledgeArticleView>>,
  'listMyAssignedTickets' : ActorMethod<[TicketQuery], Array<TicketView>>,
  'listMyNotifications' : ActorMethod<[boolean], Array<NotificationView>>,
  'listMyTickets' : ActorMethod<[TicketQuery], Array<TicketView>>,
  'listPriorities' : ActorMethod<[boolean], Array<PriorityView>>,
  'listTicketMessages' : ActorMethod<[TicketId], Array<TicketMessage>>,
  'listUsers' : ActorMethod<
    [[] | [string], [] | [AppRole], PageRequest],
    Array<UserView>
  >,
  'markAllNotificationsAsRead' : ActorMethod<[], bigint>,
  'markNotificationAsRead' : ActorMethod<[NotificationId], boolean>,
  'postTicketMessage' : ActorMethod<[TicketId, string, boolean], TicketMessage>,
  'reactivateUser' : ActorMethod<[UserId], UserView>,
  'reassignTicket' : ActorMethod<[TicketId, UserId], TicketView>,
  'schema' : ActorMethod<[], string>,
  'updateCategory' : ActorMethod<[CategoryUpdateInput], CategoryView>,
  'updateKnowledgeArticle' : ActorMethod<
    [KnowledgeArticleUpdateInput],
    KnowledgeArticleView
  >,
  'updatePriority' : ActorMethod<[PriorityUpdateInput], PriorityView>,
  'updateSystemSettings' : ActorMethod<
    [SystemSettingsUpdateInput],
    SystemSettingsView
  >,
  'updateTicket' : ActorMethod<[TicketUpdateInput], TicketView>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];