/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Principal;
export const AppRole = IDL.Variant({
  'admin' : IDL.Null,
  'l2_resolver' : IDL.Null,
  'l1_help_desk' : IDL.Null,
  'employee' : IDL.Null,
});
export const Timestamp = IDL.Nat;
export const UserView = IDL.Record({
  'id' : UserId,
  'lastSeenAt' : IDL.Opt(Timestamp),
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : AppRole,
  'isActive' : IDL.Bool,
  'email' : IDL.Opt(IDL.Text),
});
export const TicketId = IDL.Nat;
export const CategoryId = IDL.Nat;
export const TicketStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'closed' : IDL.Null,
  'pending' : IDL.Null,
  'in_progress' : IDL.Null,
  'open' : IDL.Null,
});
export const PriorityId = IDL.Nat;
export const AttachmentId = IDL.Nat;
export const Attachment = IDL.Record({
  'id' : AttachmentId,
  'mimeType' : IDL.Text,
  'fileName' : IDL.Text,
  'storageKey' : IDL.Text,
  'sizeBytes' : IDL.Nat,
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
});
export const TicketView = IDL.Record({
  'id' : TicketId,
  'categoryId' : CategoryId,
  'status' : TicketStatus,
  'predictedCategory' : IDL.Opt(CategoryId),
  'title' : IDL.Text,
  'creator' : UserId,
  'predictedPriority' : IDL.Opt(PriorityId),
  'slaDeadline' : Timestamp,
  'assignedAgent' : IDL.Opt(UserId),
  'suggestedSolution' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'duplicateOf' : IDL.Opt(TicketId),
  'updatedAt' : Timestamp,
  'closedAt' : IDL.Opt(Timestamp),
  'priorityId' : PriorityId,
  'attachments' : IDL.Vec(Attachment),
});
export const CategoryCreateInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const CategoryView = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const KnowledgeArticleCreateInput = IDL.Record({
  'categoryId' : IDL.Opt(CategoryId),
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const KnowledgeArticleId = IDL.Nat;
export const KnowledgeArticleView = IDL.Record({
  'id' : KnowledgeArticleId,
  'categoryId' : IDL.Opt(CategoryId),
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const PriorityCreateInput = IDL.Record({
  'name' : IDL.Text,
  'level' : IDL.Nat,
  'slaTargetNs' : IDL.Nat,
});
export const PriorityView = IDL.Record({
  'id' : PriorityId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'level' : IDL.Nat,
  'slaTargetNs' : IDL.Nat,
});
export const TicketCreateInput = IDL.Record({
  'categoryId' : CategoryId,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'priorityId' : PriorityId,
  'attachments' : IDL.Vec(Attachment),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ResolverTier = IDL.Variant({ 'l1' : IDL.Null, 'l2' : IDL.Null });
export const RoleKPI = IDL.Record({ 'value' : IDL.Nat, 'name' : IDL.Text });
export const ResolverQueue = IDL.Variant({
  'l1Default' : IDL.Null,
  'l2Default' : IDL.Null,
});
export const RoleDashboard = IDL.Record({
  'kpis' : IDL.Vec(RoleKPI),
  'role' : AppRole,
  'queue' : ResolverQueue,
  'queueTicketCount' : IDL.Nat,
});
export const NavItem = IDL.Record({
  'name' : IDL.Text,
  'badgeCount' : IDL.Opt(IDL.Nat),
  'route' : IDL.Text,
});
export const RoleNavigation = IDL.Record({
  'role' : AppRole,
  'items' : IDL.Vec(NavItem),
});
export const TicketSLAStatus = IDL.Record({
  'status' : TicketStatus,
  'title' : IDL.Text,
  'isAtRisk' : IDL.Bool,
  'slaDeadline' : Timestamp,
  'isBreached' : IDL.Bool,
  'timeRemainingNs' : IDL.Int,
  'ticketId' : TicketId,
  'priorityId' : PriorityId,
});
export const SystemSettingsView = IDL.Record({
  'organizationName' : IDL.Text,
  'updatedAt' : Timestamp,
  'aiFeaturesEnabled' : IDL.Bool,
});
export const TicketAnalytics = IDL.Record({
  'createdOverTime' : IDL.Vec(IDL.Tuple(Timestamp, IDL.Nat)),
  'totalTickets' : IDL.Nat,
  'byStatus' : IDL.Vec(IDL.Tuple(TicketStatus, IDL.Nat)),
  'byCategory' : IDL.Vec(IDL.Tuple(CategoryId, IDL.Nat)),
  'byPriority' : IDL.Vec(IDL.Tuple(PriorityId, IDL.Nat)),
});
export const AgentSummary = IDL.Record({
  'resolutionRate' : IDL.Float64,
  'displayName' : IDL.Text,
  'agentId' : UserId,
  'resolvedTicketCount' : IDL.Nat,
  'assignedTicketCount' : IDL.Nat,
});
export const SortOrder = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });
export const PageRequest = IDL.Record({
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
});
export const TicketQuery = IDL.Record({
  'categoryId' : IDL.Opt(CategoryId),
  'status' : IDL.Opt(TicketStatus),
  'creator' : IDL.Opt(UserId),
  'sortBy' : IDL.Opt(
    IDL.Variant({
      'createdAt' : IDL.Null,
      'updatedAt' : IDL.Null,
      'priority' : IDL.Null,
    })
  ),
  'sortOrder' : IDL.Opt(SortOrder),
  'assignedAgent' : IDL.Opt(UserId),
  'page' : PageRequest,
  'search' : IDL.Opt(IDL.Text),
  'priorityId' : IDL.Opt(PriorityId),
});
export const AuditAction = IDL.Variant({
  'priorityUpdated' : IDL.Null,
  'ticketAssigned' : IDL.Null,
  'userDeactivated' : IDL.Null,
  'categoryUpdated' : IDL.Null,
  'userReactivated' : IDL.Null,
  'settingsUpdated' : IDL.Null,
  'ticketStatusChanged' : IDL.Null,
  'ticketCreated' : IDL.Null,
  'ticketClosed' : IDL.Null,
  'roleChanged' : IDL.Null,
  'categoryCreated' : IDL.Null,
});
export const AuditLogQuery = IDL.Record({
  'toTimestamp' : IDL.Opt(Timestamp),
  'action' : IDL.Opt(AuditAction),
  'fromTimestamp' : IDL.Opt(Timestamp),
  'page' : PageRequest,
  'actorId' : IDL.Opt(UserId),
});
export const AuditLogId = IDL.Nat;
export const AuditLogView = IDL.Record({
  'id' : AuditLogId,
  'action' : AuditAction,
  'actorId' : UserId,
  'detail' : IDL.Text,
  'timestamp' : Timestamp,
  'targetEntity' : IDL.Text,
});
export const NotificationId = IDL.Nat;
export const NotificationType = IDL.Variant({
  'ticketReply' : IDL.Null,
  'ticketUpdated' : IDL.Null,
  'ticketAssigned' : IDL.Null,
  'ticketClosed' : IDL.Null,
  'roleChanged' : IDL.Null,
});
export const NotificationView = IDL.Record({
  'id' : NotificationId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'recipient' : UserId,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'linkTicketId' : IDL.Opt(TicketId),
});
export const MessageId = IDL.Nat;
export const TicketMessage = IDL.Record({
  'id' : MessageId,
  'body' : IDL.Text,
  'createdAt' : Timestamp,
  'authorRole' : AppRole,
  'ticketId' : TicketId,
  'author' : UserId,
  'isInternal' : IDL.Bool,
});
export const CategoryUpdateInput = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Opt(IDL.Bool),
});
export const KnowledgeArticleUpdateInput = IDL.Record({
  'id' : KnowledgeArticleId,
  'categoryId' : IDL.Opt(IDL.Opt(CategoryId)),
  'title' : IDL.Opt(IDL.Text),
  'content' : IDL.Opt(IDL.Text),
});
export const PriorityUpdateInput = IDL.Record({
  'id' : PriorityId,
  'name' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Opt(IDL.Bool),
  'level' : IDL.Opt(IDL.Nat),
  'slaTargetNs' : IDL.Opt(IDL.Nat),
});
export const SystemSettingsUpdateInput = IDL.Record({
  'organizationName' : IDL.Opt(IDL.Text),
  'aiFeaturesEnabled' : IDL.Opt(IDL.Bool),
});
export const TicketUpdateInput = IDL.Record({
  'status' : IDL.Opt(TicketStatus),
  'assignedAgent' : IDL.Opt(UserId),
  'resolutionSummary' : IDL.Opt(IDL.Text),
  'ticketId' : TicketId,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([UserId, AppRole], [UserView], []),
  'closeTicket' : IDL.Func([TicketId, IDL.Text], [TicketView], []),
  'countUnreadNotifications' : IDL.Func([], [IDL.Nat], ['query']),
  'createCategory' : IDL.Func([CategoryCreateInput], [CategoryView], []),
  'createKnowledgeArticle' : IDL.Func(
      [KnowledgeArticleCreateInput],
      [KnowledgeArticleView],
      [],
    ),
  'createPriority' : IDL.Func([PriorityCreateInput], [PriorityView], []),
  'createTicket' : IDL.Func([TicketCreateInput], [TicketView], []),
  'deactivateUser' : IDL.Func([UserId], [UserView], []),
  'escalateTicket' : IDL.Func([TicketId, IDL.Text], [TicketView], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getCallerAppRole' : IDL.Func([], [IDL.Opt(AppRole)], ['query']),
  'getCallerResolverTier' : IDL.Func([], [IDL.Opt(ResolverTier)], ['query']),
  'getCallerUser' : IDL.Func([], [IDL.Opt(UserView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategory' : IDL.Func([CategoryId], [IDL.Opt(CategoryView)], ['query']),
  'getKnowledgeArticle' : IDL.Func(
      [KnowledgeArticleId],
      [IDL.Opt(KnowledgeArticleView)],
      ['query'],
    ),
  'getMyQueueTickets' : IDL.Func([], [IDL.Vec(TicketView)], ['query']),
  'getMyRoleDashboard' : IDL.Func([], [RoleDashboard], ['query']),
  'getMyRoleNavigation' : IDL.Func([], [RoleNavigation], ['query']),
  'getPriority' : IDL.Func([PriorityId], [IDL.Opt(PriorityView)], ['query']),
  'getSLAStatuses' : IDL.Func([], [IDL.Vec(TicketSLAStatus)], ['query']),
  'getSystemSettings' : IDL.Func([], [SystemSettingsView], ['query']),
  'getTicket' : IDL.Func([TicketId], [IDL.Opt(TicketView)], ['query']),
  'getTicketAnalytics' : IDL.Func([], [TicketAnalytics], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(UserView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAgents' : IDL.Func([], [IDL.Vec(AgentSummary)], ['query']),
  'listAgentsByTier' : IDL.Func(
      [IDL.Opt(ResolverTier)],
      [IDL.Vec(AgentSummary)],
      ['query'],
    ),
  'listAllTickets' : IDL.Func([TicketQuery], [IDL.Vec(TicketView)], ['query']),
  'listAuditLogs' : IDL.Func(
      [AuditLogQuery],
      [IDL.Vec(AuditLogView)],
      ['query'],
    ),
  'listCategories' : IDL.Func([IDL.Bool], [IDL.Vec(CategoryView)], ['query']),
  'listKnowledgeArticles' : IDL.Func(
      [],
      [IDL.Vec(KnowledgeArticleView)],
      ['query'],
    ),
  'listMyAssignedTickets' : IDL.Func(
      [TicketQuery],
      [IDL.Vec(TicketView)],
      ['query'],
    ),
  'listMyNotifications' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(NotificationView)],
      ['query'],
    ),
  'listMyTickets' : IDL.Func([TicketQuery], [IDL.Vec(TicketView)], ['query']),
  'listPriorities' : IDL.Func([IDL.Bool], [IDL.Vec(PriorityView)], ['query']),
  'listTicketMessages' : IDL.Func(
      [TicketId],
      [IDL.Vec(TicketMessage)],
      ['query'],
    ),
  'listUsers' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(AppRole), PageRequest],
      [IDL.Vec(UserView)],
      ['query'],
    ),
  'markAllNotificationsAsRead' : IDL.Func([], [IDL.Nat], []),
  'markNotificationAsRead' : IDL.Func([NotificationId], [IDL.Bool], []),
  'postTicketMessage' : IDL.Func(
      [TicketId, IDL.Text, IDL.Bool],
      [TicketMessage],
      [],
    ),
  'reactivateUser' : IDL.Func([UserId], [UserView], []),
  'reassignTicket' : IDL.Func([TicketId, UserId], [TicketView], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateCategory' : IDL.Func([CategoryUpdateInput], [CategoryView], []),
  'updateKnowledgeArticle' : IDL.Func(
      [KnowledgeArticleUpdateInput],
      [KnowledgeArticleView],
      [],
    ),
  'updatePriority' : IDL.Func([PriorityUpdateInput], [PriorityView], []),
  'updateSystemSettings' : IDL.Func(
      [SystemSettingsUpdateInput],
      [SystemSettingsView],
      [],
    ),
  'updateTicket' : IDL.Func([TicketUpdateInput], [TicketView], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const AppRole = IDL.Variant({
    'admin' : IDL.Null,
    'l2_resolver' : IDL.Null,
    'l1_help_desk' : IDL.Null,
    'employee' : IDL.Null,
  });
  const Timestamp = IDL.Nat;
  const UserView = IDL.Record({
    'id' : UserId,
    'lastSeenAt' : IDL.Opt(Timestamp),
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : AppRole,
    'isActive' : IDL.Bool,
    'email' : IDL.Opt(IDL.Text),
  });
  const TicketId = IDL.Nat;
  const CategoryId = IDL.Nat;
  const TicketStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'closed' : IDL.Null,
    'pending' : IDL.Null,
    'in_progress' : IDL.Null,
    'open' : IDL.Null,
  });
  const PriorityId = IDL.Nat;
  const AttachmentId = IDL.Nat;
  const Attachment = IDL.Record({
    'id' : AttachmentId,
    'mimeType' : IDL.Text,
    'fileName' : IDL.Text,
    'storageKey' : IDL.Text,
    'sizeBytes' : IDL.Nat,
    'uploadedAt' : Timestamp,
    'uploadedBy' : UserId,
  });
  const TicketView = IDL.Record({
    'id' : TicketId,
    'categoryId' : CategoryId,
    'status' : TicketStatus,
    'predictedCategory' : IDL.Opt(CategoryId),
    'title' : IDL.Text,
    'creator' : UserId,
    'predictedPriority' : IDL.Opt(PriorityId),
    'slaDeadline' : Timestamp,
    'assignedAgent' : IDL.Opt(UserId),
    'suggestedSolution' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'duplicateOf' : IDL.Opt(TicketId),
    'updatedAt' : Timestamp,
    'closedAt' : IDL.Opt(Timestamp),
    'priorityId' : PriorityId,
    'attachments' : IDL.Vec(Attachment),
  });
  const CategoryCreateInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const CategoryView = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const KnowledgeArticleCreateInput = IDL.Record({
    'categoryId' : IDL.Opt(CategoryId),
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const KnowledgeArticleId = IDL.Nat;
  const KnowledgeArticleView = IDL.Record({
    'id' : KnowledgeArticleId,
    'categoryId' : IDL.Opt(CategoryId),
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const PriorityCreateInput = IDL.Record({
    'name' : IDL.Text,
    'level' : IDL.Nat,
    'slaTargetNs' : IDL.Nat,
  });
  const PriorityView = IDL.Record({
    'id' : PriorityId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'level' : IDL.Nat,
    'slaTargetNs' : IDL.Nat,
  });
  const TicketCreateInput = IDL.Record({
    'categoryId' : CategoryId,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'priorityId' : PriorityId,
    'attachments' : IDL.Vec(Attachment),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ResolverTier = IDL.Variant({ 'l1' : IDL.Null, 'l2' : IDL.Null });
  const RoleKPI = IDL.Record({ 'value' : IDL.Nat, 'name' : IDL.Text });
  const ResolverQueue = IDL.Variant({
    'l1Default' : IDL.Null,
    'l2Default' : IDL.Null,
  });
  const RoleDashboard = IDL.Record({
    'kpis' : IDL.Vec(RoleKPI),
    'role' : AppRole,
    'queue' : ResolverQueue,
    'queueTicketCount' : IDL.Nat,
  });
  const NavItem = IDL.Record({
    'name' : IDL.Text,
    'badgeCount' : IDL.Opt(IDL.Nat),
    'route' : IDL.Text,
  });
  const RoleNavigation = IDL.Record({
    'role' : AppRole,
    'items' : IDL.Vec(NavItem),
  });
  const TicketSLAStatus = IDL.Record({
    'status' : TicketStatus,
    'title' : IDL.Text,
    'isAtRisk' : IDL.Bool,
    'slaDeadline' : Timestamp,
    'isBreached' : IDL.Bool,
    'timeRemainingNs' : IDL.Int,
    'ticketId' : TicketId,
    'priorityId' : PriorityId,
  });
  const SystemSettingsView = IDL.Record({
    'organizationName' : IDL.Text,
    'updatedAt' : Timestamp,
    'aiFeaturesEnabled' : IDL.Bool,
  });
  const TicketAnalytics = IDL.Record({
    'createdOverTime' : IDL.Vec(IDL.Tuple(Timestamp, IDL.Nat)),
    'totalTickets' : IDL.Nat,
    'byStatus' : IDL.Vec(IDL.Tuple(TicketStatus, IDL.Nat)),
    'byCategory' : IDL.Vec(IDL.Tuple(CategoryId, IDL.Nat)),
    'byPriority' : IDL.Vec(IDL.Tuple(PriorityId, IDL.Nat)),
  });
  const AgentSummary = IDL.Record({
    'resolutionRate' : IDL.Float64,
    'displayName' : IDL.Text,
    'agentId' : UserId,
    'resolvedTicketCount' : IDL.Nat,
    'assignedTicketCount' : IDL.Nat,
  });
  const SortOrder = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });
  const PageRequest = IDL.Record({ 'page' : IDL.Nat, 'pageSize' : IDL.Nat });
  const TicketQuery = IDL.Record({
    'categoryId' : IDL.Opt(CategoryId),
    'status' : IDL.Opt(TicketStatus),
    'creator' : IDL.Opt(UserId),
    'sortBy' : IDL.Opt(
      IDL.Variant({
        'createdAt' : IDL.Null,
        'updatedAt' : IDL.Null,
        'priority' : IDL.Null,
      })
    ),
    'sortOrder' : IDL.Opt(SortOrder),
    'assignedAgent' : IDL.Opt(UserId),
    'page' : PageRequest,
    'search' : IDL.Opt(IDL.Text),
    'priorityId' : IDL.Opt(PriorityId),
  });
  const AuditAction = IDL.Variant({
    'priorityUpdated' : IDL.Null,
    'ticketAssigned' : IDL.Null,
    'userDeactivated' : IDL.Null,
    'categoryUpdated' : IDL.Null,
    'userReactivated' : IDL.Null,
    'settingsUpdated' : IDL.Null,
    'ticketStatusChanged' : IDL.Null,
    'ticketCreated' : IDL.Null,
    'ticketClosed' : IDL.Null,
    'roleChanged' : IDL.Null,
    'categoryCreated' : IDL.Null,
  });
  const AuditLogQuery = IDL.Record({
    'toTimestamp' : IDL.Opt(Timestamp),
    'action' : IDL.Opt(AuditAction),
    'fromTimestamp' : IDL.Opt(Timestamp),
    'page' : PageRequest,
    'actorId' : IDL.Opt(UserId),
  });
  const AuditLogId = IDL.Nat;
  const AuditLogView = IDL.Record({
    'id' : AuditLogId,
    'action' : AuditAction,
    'actorId' : UserId,
    'detail' : IDL.Text,
    'timestamp' : Timestamp,
    'targetEntity' : IDL.Text,
  });
  const NotificationId = IDL.Nat;
  const NotificationType = IDL.Variant({
    'ticketReply' : IDL.Null,
    'ticketUpdated' : IDL.Null,
    'ticketAssigned' : IDL.Null,
    'ticketClosed' : IDL.Null,
    'roleChanged' : IDL.Null,
  });
  const NotificationView = IDL.Record({
    'id' : NotificationId,
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'recipient' : UserId,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'linkTicketId' : IDL.Opt(TicketId),
  });
  const MessageId = IDL.Nat;
  const TicketMessage = IDL.Record({
    'id' : MessageId,
    'body' : IDL.Text,
    'createdAt' : Timestamp,
    'authorRole' : AppRole,
    'ticketId' : TicketId,
    'author' : UserId,
    'isInternal' : IDL.Bool,
  });
  const CategoryUpdateInput = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Opt(IDL.Bool),
  });
  const KnowledgeArticleUpdateInput = IDL.Record({
    'id' : KnowledgeArticleId,
    'categoryId' : IDL.Opt(IDL.Opt(CategoryId)),
    'title' : IDL.Opt(IDL.Text),
    'content' : IDL.Opt(IDL.Text),
  });
  const PriorityUpdateInput = IDL.Record({
    'id' : PriorityId,
    'name' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Opt(IDL.Bool),
    'level' : IDL.Opt(IDL.Nat),
    'slaTargetNs' : IDL.Opt(IDL.Nat),
  });
  const SystemSettingsUpdateInput = IDL.Record({
    'organizationName' : IDL.Opt(IDL.Text),
    'aiFeaturesEnabled' : IDL.Opt(IDL.Bool),
  });
  const TicketUpdateInput = IDL.Record({
    'status' : IDL.Opt(TicketStatus),
    'assignedAgent' : IDL.Opt(UserId),
    'resolutionSummary' : IDL.Opt(IDL.Text),
    'ticketId' : TicketId,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([UserId, AppRole], [UserView], []),
    'closeTicket' : IDL.Func([TicketId, IDL.Text], [TicketView], []),
    'countUnreadNotifications' : IDL.Func([], [IDL.Nat], ['query']),
    'createCategory' : IDL.Func([CategoryCreateInput], [CategoryView], []),
    'createKnowledgeArticle' : IDL.Func(
        [KnowledgeArticleCreateInput],
        [KnowledgeArticleView],
        [],
      ),
    'createPriority' : IDL.Func([PriorityCreateInput], [PriorityView], []),
    'createTicket' : IDL.Func([TicketCreateInput], [TicketView], []),
    'deactivateUser' : IDL.Func([UserId], [UserView], []),
    'escalateTicket' : IDL.Func([TicketId, IDL.Text], [TicketView], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getCallerAppRole' : IDL.Func([], [IDL.Opt(AppRole)], ['query']),
    'getCallerResolverTier' : IDL.Func([], [IDL.Opt(ResolverTier)], ['query']),
    'getCallerUser' : IDL.Func([], [IDL.Opt(UserView)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategory' : IDL.Func([CategoryId], [IDL.Opt(CategoryView)], ['query']),
    'getKnowledgeArticle' : IDL.Func(
        [KnowledgeArticleId],
        [IDL.Opt(KnowledgeArticleView)],
        ['query'],
      ),
    'getMyQueueTickets' : IDL.Func([], [IDL.Vec(TicketView)], ['query']),
    'getMyRoleDashboard' : IDL.Func([], [RoleDashboard], ['query']),
    'getMyRoleNavigation' : IDL.Func([], [RoleNavigation], ['query']),
    'getPriority' : IDL.Func([PriorityId], [IDL.Opt(PriorityView)], ['query']),
    'getSLAStatuses' : IDL.Func([], [IDL.Vec(TicketSLAStatus)], ['query']),
    'getSystemSettings' : IDL.Func([], [SystemSettingsView], ['query']),
    'getTicket' : IDL.Func([TicketId], [IDL.Opt(TicketView)], ['query']),
    'getTicketAnalytics' : IDL.Func([], [TicketAnalytics], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(UserView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAgents' : IDL.Func([], [IDL.Vec(AgentSummary)], ['query']),
    'listAgentsByTier' : IDL.Func(
        [IDL.Opt(ResolverTier)],
        [IDL.Vec(AgentSummary)],
        ['query'],
      ),
    'listAllTickets' : IDL.Func(
        [TicketQuery],
        [IDL.Vec(TicketView)],
        ['query'],
      ),
    'listAuditLogs' : IDL.Func(
        [AuditLogQuery],
        [IDL.Vec(AuditLogView)],
        ['query'],
      ),
    'listCategories' : IDL.Func([IDL.Bool], [IDL.Vec(CategoryView)], ['query']),
    'listKnowledgeArticles' : IDL.Func(
        [],
        [IDL.Vec(KnowledgeArticleView)],
        ['query'],
      ),
    'listMyAssignedTickets' : IDL.Func(
        [TicketQuery],
        [IDL.Vec(TicketView)],
        ['query'],
      ),
    'listMyNotifications' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(NotificationView)],
        ['query'],
      ),
    'listMyTickets' : IDL.Func([TicketQuery], [IDL.Vec(TicketView)], ['query']),
    'listPriorities' : IDL.Func([IDL.Bool], [IDL.Vec(PriorityView)], ['query']),
    'listTicketMessages' : IDL.Func(
        [TicketId],
        [IDL.Vec(TicketMessage)],
        ['query'],
      ),
    'listUsers' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(AppRole), PageRequest],
        [IDL.Vec(UserView)],
        ['query'],
      ),
    'markAllNotificationsAsRead' : IDL.Func([], [IDL.Nat], []),
    'markNotificationAsRead' : IDL.Func([NotificationId], [IDL.Bool], []),
    'postTicketMessage' : IDL.Func(
        [TicketId, IDL.Text, IDL.Bool],
        [TicketMessage],
        [],
      ),
    'reactivateUser' : IDL.Func([UserId], [UserView], []),
    'reassignTicket' : IDL.Func([TicketId, UserId], [TicketView], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateCategory' : IDL.Func([CategoryUpdateInput], [CategoryView], []),
    'updateKnowledgeArticle' : IDL.Func(
        [KnowledgeArticleUpdateInput],
        [KnowledgeArticleView],
        [],
      ),
    'updatePriority' : IDL.Func([PriorityUpdateInput], [PriorityView], []),
    'updateSystemSettings' : IDL.Func(
        [SystemSettingsUpdateInput],
        [SystemSettingsView],
        [],
      ),
    'updateTicket' : IDL.Func([TicketUpdateInput], [TicketView], []),
  });
};

export const init = ({ IDL }) => { return []; };