/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Attachment {
    id: AttachmentId;
    mimeType: string;
    fileName: string;
    storageKey: string;
    sizeBytes: bigint;
    uploadedAt: Timestamp;
    uploadedBy: UserId;
}
export type Timestamp = bigint;
export interface PriorityCreateInput {
    name: string;
    level: bigint;
    slaTargetNs: bigint;
}
export interface TicketCreateInput {
    categoryId: CategoryId;
    title: string;
    description: string;
    priorityId: PriorityId;
    attachments: Array<Attachment>;
}
export interface UserView {
    id: UserId;
    lastSeenAt?: Timestamp;
    displayName: string;
    createdAt: Timestamp;
    role: AppRole;
    isActive: boolean;
    email?: string;
}
export interface TicketSLAStatus {
    status: TicketStatus;
    title: string;
    isAtRisk: boolean;
    slaDeadline: Timestamp;
    isBreached: boolean;
    timeRemainingNs: bigint;
    ticketId: TicketId;
    priorityId: PriorityId;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type AuditLogId = bigint;
export interface AgentSummary {
    resolutionRate: number;
    displayName: string;
    agentId: UserId;
    resolvedTicketCount: bigint;
    assignedTicketCount: bigint;
}
export type TicketId = bigint;
export interface NotificationView {
    id: NotificationId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    recipient: UserId;
    isRead: boolean;
    message: string;
    linkTicketId?: TicketId;
}
export type KnowledgeArticleId = bigint;
export type PriorityId = bigint;
export interface RoleKPI {
    value: bigint;
    name: string;
}
export interface SystemSettingsUpdateInput {
    organizationName?: string;
    aiFeaturesEnabled?: boolean;
}
export interface PriorityView {
    id: PriorityId;
    name: string;
    createdAt: Timestamp;
    isActive: boolean;
    level: bigint;
    slaTargetNs: bigint;
}
export interface PriorityUpdateInput {
    id: PriorityId;
    name?: string;
    isActive?: boolean;
    level?: bigint;
    slaTargetNs?: bigint;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface TicketQuery {
    categoryId?: CategoryId;
    status?: TicketStatus;
    creator?: UserId;
    sortBy?: Variant_createdAt_updatedAt_priority;
    sortOrder?: SortOrder;
    assignedAgent?: UserId;
    page: PageRequest;
    search?: string;
    priorityId?: PriorityId;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface TicketView {
    id: TicketId;
    categoryId: CategoryId;
    status: TicketStatus;
    predictedCategory?: CategoryId;
    title: string;
    creator: UserId;
    predictedPriority?: PriorityId;
    slaDeadline: Timestamp;
    assignedAgent?: UserId;
    suggestedSolution?: string;
    createdAt: Timestamp;
    description: string;
    duplicateOf?: TicketId;
    updatedAt: Timestamp;
    closedAt?: Timestamp;
    priorityId: PriorityId;
    attachments: Array<Attachment>;
}
export interface CategoryCreateInput {
    name: string;
    description: string;
}
export interface RoleNavigation {
    role: AppRole;
    items: Array<NavItem>;
}
export interface AuditLogQuery {
    toTimestamp?: Timestamp;
    action?: AuditAction;
    fromTimestamp?: Timestamp;
    page: PageRequest;
    actorId?: UserId;
}
export interface PageRequest {
    page: bigint;
    pageSize: bigint;
}
export interface CategoryUpdateInput {
    id: CategoryId;
    name?: string;
    description?: string;
    isActive?: boolean;
}
export interface KnowledgeArticleCreateInput {
    categoryId?: CategoryId;
    title: string;
    content: string;
}
export interface TicketAnalytics {
    createdOverTime: Array<[Timestamp, bigint]>;
    totalTickets: bigint;
    byStatus: Array<[TicketStatus, bigint]>;
    byCategory: Array<[CategoryId, bigint]>;
    byPriority: Array<[PriorityId, bigint]>;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface KnowledgeArticleView {
    id: KnowledgeArticleId;
    categoryId?: CategoryId;
    title: string;
    content: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
}
export type AttachmentId = bigint;
export interface KnowledgeArticleUpdateInput {
    id: KnowledgeArticleId;
    categoryId?: CategoryId | null;
    title?: string;
    content?: string;
}
export type UserId = Principal;
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface SystemSettingsView {
    organizationName: string;
    updatedAt: Timestamp;
    aiFeaturesEnabled: boolean;
}
export interface NavItem {
    name: string;
    badgeCount?: bigint;
    route: string;
}
export type NotificationId = bigint;
export interface TicketUpdateInput {
    status?: TicketStatus;
    assignedAgent?: UserId;
    resolutionSummary?: string;
    ticketId: TicketId;
}
export type MessageId = bigint;
export type CategoryId = bigint;
export interface AuditLogView {
    id: AuditLogId;
    action: AuditAction;
    actorId: UserId;
    detail: string;
    timestamp: Timestamp;
    targetEntity: string;
}
export interface RoleDashboard {
    kpis: Array<RoleKPI>;
    role: AppRole;
    queue: ResolverQueue;
    queueTicketCount: bigint;
}
export interface CategoryView {
    id: CategoryId;
    name: string;
    createdAt: Timestamp;
    description: string;
    isActive: boolean;
}
export interface TicketMessage {
    id: MessageId;
    body: string;
    createdAt: Timestamp;
    authorRole: AppRole;
    ticketId: TicketId;
    author: UserId;
    isInternal: boolean;
}
export enum AppRole {
    admin = "admin",
    l2_resolver = "l2_resolver",
    l1_help_desk = "l1_help_desk",
    employee = "employee"
}
export enum AuditAction {
    priorityUpdated = "priorityUpdated",
    ticketAssigned = "ticketAssigned",
    userDeactivated = "userDeactivated",
    categoryUpdated = "categoryUpdated",
    userReactivated = "userReactivated",
    settingsUpdated = "settingsUpdated",
    ticketStatusChanged = "ticketStatusChanged",
    ticketCreated = "ticketCreated",
    ticketClosed = "ticketClosed",
    roleChanged = "roleChanged",
    categoryCreated = "categoryCreated"
}
export enum NotificationType {
    ticketReply = "ticketReply",
    ticketUpdated = "ticketUpdated",
    ticketAssigned = "ticketAssigned",
    ticketClosed = "ticketClosed",
    roleChanged = "roleChanged"
}
export enum ResolverQueue {
    l1Default = "l1Default",
    l2Default = "l2Default"
}
export enum ResolverTier {
    l1 = "l1",
    l2 = "l2"
}
export enum SortOrder {
    asc = "asc",
    desc = "desc"
}
export enum TicketStatus {
    resolved = "resolved",
    closed = "closed",
    pending = "pending",
    in_progress = "in_progress",
    open = "open"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_createdAt_updatedAt_priority {
    createdAt = "createdAt",
    updatedAt = "updatedAt",
    priority = "priority"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignUserRole(user: UserId, newRole: AppRole): Promise<UserView>;
    closeTicket(ticketId: TicketId, resolutionSummary: string): Promise<TicketView>;
    countUnreadNotifications(): Promise<bigint>;
    createCategory(input: CategoryCreateInput): Promise<CategoryView>;
    createKnowledgeArticle(input: KnowledgeArticleCreateInput): Promise<KnowledgeArticleView>;
    createPriority(input: PriorityCreateInput): Promise<PriorityView>;
    createTicket(input: TicketCreateInput): Promise<TicketView>;
    deactivateUser(user: UserId): Promise<UserView>;
    escalateTicket(ticketId: TicketId, reason: string): Promise<TicketView>;
    execute(qJson: string): Promise<Result>;
    getCallerAppRole(): Promise<AppRole | null>;
    getCallerResolverTier(): Promise<ResolverTier | null>;
    getCallerUser(): Promise<UserView | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategory(id: CategoryId): Promise<CategoryView | null>;
    getKnowledgeArticle(id: KnowledgeArticleId): Promise<KnowledgeArticleView | null>;
    getMyQueueTickets(): Promise<Array<TicketView>>;
    getMyRoleDashboard(): Promise<RoleDashboard>;
    getMyRoleNavigation(): Promise<RoleNavigation>;
    getPriority(id: PriorityId): Promise<PriorityView | null>;
    getSLAStatuses(): Promise<Array<TicketSLAStatus>>;
    getSystemSettings(): Promise<SystemSettingsView>;
    getTicket(id: TicketId): Promise<TicketView | null>;
    getTicketAnalytics(): Promise<TicketAnalytics>;
    getUser(id: UserId): Promise<UserView | null>;
    isCallerAdmin(): Promise<boolean>;
    listAgents(): Promise<Array<AgentSummary>>;
    listAgentsByTier(tier: ResolverTier | null): Promise<Array<AgentSummary>>;
    listAllTickets(ticketQuery: TicketQuery): Promise<Array<TicketView>>;
    listAuditLogs(auditQuery: AuditLogQuery): Promise<Array<AuditLogView>>;
    listCategories(includeInactive: boolean): Promise<Array<CategoryView>>;
    listKnowledgeArticles(): Promise<Array<KnowledgeArticleView>>;
    listMyAssignedTickets(ticketQuery: TicketQuery): Promise<Array<TicketView>>;
    listMyNotifications(includeRead: boolean): Promise<Array<NotificationView>>;
    listMyTickets(ticketQuery: TicketQuery): Promise<Array<TicketView>>;
    listPriorities(includeInactive: boolean): Promise<Array<PriorityView>>;
    listTicketMessages(ticketId: TicketId): Promise<Array<TicketMessage>>;
    listUsers(search: string | null, roleFilter: AppRole | null, page: PageRequest): Promise<Array<UserView>>;
    markAllNotificationsAsRead(): Promise<bigint>;
    markNotificationAsRead(id: NotificationId): Promise<boolean>;
    postTicketMessage(ticketId: TicketId, body: string, isInternal: boolean): Promise<TicketMessage>;
    reactivateUser(user: UserId): Promise<UserView>;
    reassignTicket(ticketId: TicketId, newAgent: UserId): Promise<TicketView>;
    schema(): Promise<string>;
    updateCategory(input: CategoryUpdateInput): Promise<CategoryView>;
    updateKnowledgeArticle(input: KnowledgeArticleUpdateInput): Promise<KnowledgeArticleView>;
    updatePriority(input: PriorityUpdateInput): Promise<PriorityView>;
    updateSystemSettings(input: SystemSettingsUpdateInput): Promise<SystemSettingsView>;
    updateTicket(input: TicketUpdateInput): Promise<TicketView>;
}
import type { AppRole as _AppRole, Attachment as _Attachment, AuditAction as _AuditAction, AuditLogId as _AuditLogId, AuditLogQuery as _AuditLogQuery, AuditLogView as _AuditLogView, CategoryId as _CategoryId, CategoryUpdateInput as _CategoryUpdateInput, CategoryView as _CategoryView, Cell as _Cell, Error as _Error, KnowledgeArticleCreateInput as _KnowledgeArticleCreateInput, KnowledgeArticleId as _KnowledgeArticleId, KnowledgeArticleUpdateInput as _KnowledgeArticleUpdateInput, KnowledgeArticleView as _KnowledgeArticleView, MessageId as _MessageId, NavItem as _NavItem, NotificationId as _NotificationId, NotificationType as _NotificationType, NotificationView as _NotificationView, PageRequest as _PageRequest, PriorityId as _PriorityId, PriorityUpdateInput as _PriorityUpdateInput, PriorityView as _PriorityView, ResolverQueue as _ResolverQueue, ResolverTier as _ResolverTier, Result as _Result, Result__1 as _Result__1, RoleDashboard as _RoleDashboard, RoleKPI as _RoleKPI, RoleNavigation as _RoleNavigation, SortOrder as _SortOrder, SystemSettingsUpdateInput as _SystemSettingsUpdateInput, TicketAnalytics as _TicketAnalytics, TicketId as _TicketId, TicketMessage as _TicketMessage, TicketQuery as _TicketQuery, TicketSLAStatus as _TicketSLAStatus, TicketStatus as _TicketStatus, TicketUpdateInput as _TicketUpdateInput, TicketView as _TicketView, Timestamp as _Timestamp, UserId as _UserId, UserRole as _UserRole, UserView as _UserView, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignUserRole(arg0: UserId, arg1: AppRole): Promise<UserView> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserRole(arg0, to_candid_AppRole_n7(this._uploadFile, this._downloadFile, arg1));
                return from_candid_UserView_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserRole(arg0, to_candid_AppRole_n7(this._uploadFile, this._downloadFile, arg1));
            return from_candid_UserView_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async closeTicket(arg0: TicketId, arg1: string): Promise<TicketView> {
        if (this.processError) {
            try {
                const result = await this.actor.closeTicket(arg0, arg1);
                return from_candid_TicketView_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeTicket(arg0, arg1);
            return from_candid_TicketView_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async countUnreadNotifications(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.countUnreadNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.countUnreadNotifications();
            return result;
        }
    }
    async createCategory(arg0: CategoryCreateInput): Promise<CategoryView> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0);
            return result;
        }
    }
    async createKnowledgeArticle(arg0: KnowledgeArticleCreateInput): Promise<KnowledgeArticleView> {
        if (this.processError) {
            try {
                const result = await this.actor.createKnowledgeArticle(to_candid_KnowledgeArticleCreateInput_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_KnowledgeArticleView_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createKnowledgeArticle(to_candid_KnowledgeArticleCreateInput_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_KnowledgeArticleView_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPriority(arg0: PriorityCreateInput): Promise<PriorityView> {
        if (this.processError) {
            try {
                const result = await this.actor.createPriority(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPriority(arg0);
            return result;
        }
    }
    async createTicket(arg0: TicketCreateInput): Promise<TicketView> {
        if (this.processError) {
            try {
                const result = await this.actor.createTicket(arg0);
                return from_candid_TicketView_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTicket(arg0);
            return from_candid_TicketView_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async deactivateUser(arg0: UserId): Promise<UserView> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUser(arg0);
                return from_candid_UserView_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUser(arg0);
            return from_candid_UserView_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async escalateTicket(arg0: TicketId, arg1: string): Promise<TicketView> {
        if (this.processError) {
            try {
                const result = await this.actor.escalateTicket(arg0, arg1);
                return from_candid_TicketView_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.escalateTicket(arg0, arg1);
            return from_candid_TicketView_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerAppRole(): Promise<AppRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAppRole();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAppRole();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerResolverTier(): Promise<ResolverTier | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerResolverTier();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerResolverTier();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUser(): Promise<UserView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUser();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUser();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategory(arg0: CategoryId): Promise<CategoryView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategory(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategory(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKnowledgeArticle(arg0: KnowledgeArticleId): Promise<KnowledgeArticleView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKnowledgeArticle(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKnowledgeArticle(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyQueueTickets(): Promise<Array<TicketView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyQueueTickets();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyQueueTickets();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRoleDashboard(): Promise<RoleDashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRoleDashboard();
                return from_candid_RoleDashboard_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRoleDashboard();
            return from_candid_RoleDashboard_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRoleNavigation(): Promise<RoleNavigation> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRoleNavigation();
                return from_candid_RoleNavigation_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRoleNavigation();
            return from_candid_RoleNavigation_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPriority(arg0: PriorityId): Promise<PriorityView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriority(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriority(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSLAStatuses(): Promise<Array<TicketSLAStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSLAStatuses();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSLAStatuses();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystemSettings(): Promise<SystemSettingsView> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemSettings();
            return result;
        }
    }
    async getTicket(arg0: TicketId): Promise<TicketView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicket(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicket(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTicketAnalytics(): Promise<TicketAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicketAnalytics();
                return from_candid_TicketAnalytics_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicketAnalytics();
            return from_candid_TicketAnalytics_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: UserId): Promise<UserView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAgents(): Promise<Array<AgentSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAgents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAgents();
            return result;
        }
    }
    async listAgentsByTier(arg0: ResolverTier | null): Promise<Array<AgentSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAgentsByTier(to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAgentsByTier(to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async listAllTickets(arg0: TicketQuery): Promise<Array<TicketView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllTickets(to_candid_TicketQuery_n67(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllTickets(to_candid_TicketQuery_n67(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAuditLogs(arg0: AuditLogQuery): Promise<Array<AuditLogView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAuditLogs(to_candid_AuditLogQuery_n74(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAuditLogs(to_candid_AuditLogQuery_n74(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCategories(arg0: boolean): Promise<Array<CategoryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCategories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCategories(arg0);
            return result;
        }
    }
    async listKnowledgeArticles(): Promise<Array<KnowledgeArticleView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listKnowledgeArticles();
                return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listKnowledgeArticles();
            return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyAssignedTickets(arg0: TicketQuery): Promise<Array<TicketView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyAssignedTickets(to_candid_TicketQuery_n67(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyAssignedTickets(to_candid_TicketQuery_n67(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyNotifications(arg0: boolean): Promise<Array<NotificationView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyNotifications(arg0);
                return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyNotifications(arg0);
            return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyTickets(arg0: TicketQuery): Promise<Array<TicketView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyTickets(to_candid_TicketQuery_n67(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyTickets(to_candid_TicketQuery_n67(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPriorities(arg0: boolean): Promise<Array<PriorityView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPriorities(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPriorities(arg0);
            return result;
        }
    }
    async listTicketMessages(arg0: TicketId): Promise<Array<TicketMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTicketMessages(arg0);
                return from_candid_vec_n89(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTicketMessages(arg0);
            return from_candid_vec_n89(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(arg0: string | null, arg1: AppRole | null, arg2: PageRequest): Promise<Array<UserView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers(to_candid_opt_n92(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n93(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_vec_n94(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers(to_candid_opt_n92(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n93(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_vec_n94(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsAsRead(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsAsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsAsRead();
            return result;
        }
    }
    async markNotificationAsRead(arg0: NotificationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async postTicketMessage(arg0: TicketId, arg1: string, arg2: boolean): Promise<TicketMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.postTicketMessage(arg0, arg1, arg2);
                return from_candid_TicketMessage_n90(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postTicketMessage(arg0, arg1, arg2);
            return from_candid_TicketMessage_n90(this._uploadFile, this._downloadFile, result);
        }
    }
    async reactivateUser(arg0: UserId): Promise<UserView> {
        if (this.processError) {
            try {
                const result = await this.actor.reactivateUser(arg0);
                return from_candid_UserView_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reactivateUser(arg0);
            return from_candid_UserView_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async reassignTicket(arg0: TicketId, arg1: UserId): Promise<TicketView> {
        if (this.processError) {
            try {
                const result = await this.actor.reassignTicket(arg0, arg1);
                return from_candid_TicketView_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reassignTicket(arg0, arg1);
            return from_candid_TicketView_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async updateCategory(arg0: CategoryUpdateInput): Promise<CategoryView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(to_candid_CategoryUpdateInput_n95(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(to_candid_CategoryUpdateInput_n95(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateKnowledgeArticle(arg0: KnowledgeArticleUpdateInput): Promise<KnowledgeArticleView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKnowledgeArticle(to_candid_KnowledgeArticleUpdateInput_n97(this._uploadFile, this._downloadFile, arg0));
                return from_candid_KnowledgeArticleView_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKnowledgeArticle(to_candid_KnowledgeArticleUpdateInput_n97(this._uploadFile, this._downloadFile, arg0));
            return from_candid_KnowledgeArticleView_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePriority(arg0: PriorityUpdateInput): Promise<PriorityView> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePriority(to_candid_PriorityUpdateInput_n100(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePriority(to_candid_PriorityUpdateInput_n100(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSystemSettings(arg0: SystemSettingsUpdateInput): Promise<SystemSettingsView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSystemSettings(to_candid_SystemSettingsUpdateInput_n102(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSystemSettings(to_candid_SystemSettingsUpdateInput_n102(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTicket(arg0: TicketUpdateInput): Promise<TicketView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTicket(to_candid_TicketUpdateInput_n104(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TicketView_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTicket(to_candid_TicketUpdateInput_n104(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TicketView_n15(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_AuditAction_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditAction): AuditAction {
    return from_candid_variant_n82(_uploadFile, _downloadFile, value);
}
function from_candid_AuditLogView_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditLogView): AuditLogView {
    return from_candid_record_n80(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_KnowledgeArticleView_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KnowledgeArticleView): KnowledgeArticleView {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_NavItem_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NavItem): NavItem {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n88(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationView_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationView): NotificationView {
    return from_candid_record_n86(_uploadFile, _downloadFile, value);
}
function from_candid_ResolverQueue_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResolverQueue): ResolverQueue {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_ResolverTier_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResolverTier): ResolverTier {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_RoleDashboard_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoleDashboard): RoleDashboard {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_RoleNavigation_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoleNavigation): RoleNavigation {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_TicketAnalytics_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketAnalytics): TicketAnalytics {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
function from_candid_TicketMessage_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketMessage): TicketMessage {
    return from_candid_record_n91(_uploadFile, _downloadFile, value);
}
function from_candid_TicketSLAStatus_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketSLAStatus): TicketSLAStatus {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_TicketStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketStatus): TicketStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TicketView_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketView): TicketView {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserView_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserView): UserView {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CategoryId]): CategoryId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PriorityId]): PriorityId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TicketId]): TicketId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppRole]): AppRole | null {
    return value.length === 0 ? null : from_candid_AppRole_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResolverTier]): ResolverTier | null {
    return value.length === 0 ? null : from_candid_ResolverTier_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserView]): UserView | null {
    return value.length === 0 ? null : from_candid_UserView_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CategoryView]): CategoryView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_KnowledgeArticleView]): KnowledgeArticleView | null {
    return value.length === 0 ? null : from_candid_KnowledgeArticleView_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PriorityView]): PriorityView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TicketView]): TicketView | null {
    return value.length === 0 ? null : from_candid_TicketView_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    lastSeenAt: [] | [_Timestamp];
    displayName: string;
    createdAt: _Timestamp;
    role: _AppRole;
    isActive: boolean;
    email: [] | [string];
}): {
    id: UserId;
    lastSeenAt?: Timestamp;
    displayName: string;
    createdAt: Timestamp;
    role: AppRole;
    isActive: boolean;
    email?: string;
} {
    return {
        id: value.id,
        lastSeenAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.lastSeenAt)),
        displayName: value.displayName,
        createdAt: value.createdAt,
        role: from_candid_AppRole_n12(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TicketId;
    categoryId: _CategoryId;
    status: _TicketStatus;
    predictedCategory: [] | [_CategoryId];
    title: string;
    creator: _UserId;
    predictedPriority: [] | [_PriorityId];
    slaDeadline: _Timestamp;
    assignedAgent: [] | [_UserId];
    suggestedSolution: [] | [string];
    createdAt: _Timestamp;
    description: string;
    duplicateOf: [] | [_TicketId];
    updatedAt: _Timestamp;
    closedAt: [] | [_Timestamp];
    priorityId: _PriorityId;
    attachments: Array<_Attachment>;
}): {
    id: TicketId;
    categoryId: CategoryId;
    status: TicketStatus;
    predictedCategory?: CategoryId;
    title: string;
    creator: UserId;
    predictedPriority?: PriorityId;
    slaDeadline: Timestamp;
    assignedAgent?: UserId;
    suggestedSolution?: string;
    createdAt: Timestamp;
    description: string;
    duplicateOf?: TicketId;
    updatedAt: Timestamp;
    closedAt?: Timestamp;
    priorityId: PriorityId;
    attachments: Array<Attachment>;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        status: from_candid_TicketStatus_n17(_uploadFile, _downloadFile, value.status),
        predictedCategory: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.predictedCategory)),
        title: value.title,
        creator: value.creator,
        predictedPriority: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.predictedPriority)),
        slaDeadline: value.slaDeadline,
        assignedAgent: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.assignedAgent)),
        suggestedSolution: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.suggestedSolution)),
        createdAt: value.createdAt,
        description: value.description,
        duplicateOf: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.duplicateOf)),
        updatedAt: value.updatedAt,
        closedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.closedAt)),
        priorityId: value.priorityId,
        attachments: value.attachments
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _KnowledgeArticleId;
    categoryId: [] | [_CategoryId];
    title: string;
    content: string;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
}): {
    id: KnowledgeArticleId;
    categoryId?: CategoryId;
    title: string;
    content: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
} {
    return {
        id: value.id,
        categoryId: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.categoryId)),
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n29(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n33(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kpis: Array<_RoleKPI>;
    role: _AppRole;
    queue: _ResolverQueue;
    queueTicketCount: bigint;
}): {
    kpis: Array<RoleKPI>;
    role: AppRole;
    queue: ResolverQueue;
    queueTicketCount: bigint;
} {
    return {
        kpis: value.kpis,
        role: from_candid_AppRole_n12(_uploadFile, _downloadFile, value.role),
        queue: from_candid_ResolverQueue_n47(_uploadFile, _downloadFile, value.queue),
        queueTicketCount: value.queueTicketCount
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: _AppRole;
    items: Array<_NavItem>;
}): {
    role: AppRole;
    items: Array<NavItem>;
} {
    return {
        role: from_candid_AppRole_n12(_uploadFile, _downloadFile, value.role),
        items: from_candid_vec_n51(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    badgeCount: [] | [bigint];
    route: string;
}): {
    name: string;
    badgeCount?: bigint;
    route: string;
} {
    return {
        name: value.name,
        badgeCount: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.badgeCount)),
        route: value.route
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TicketStatus;
    title: string;
    isAtRisk: boolean;
    slaDeadline: _Timestamp;
    isBreached: boolean;
    timeRemainingNs: bigint;
    ticketId: _TicketId;
    priorityId: _PriorityId;
}): {
    status: TicketStatus;
    title: string;
    isAtRisk: boolean;
    slaDeadline: Timestamp;
    isBreached: boolean;
    timeRemainingNs: bigint;
    ticketId: TicketId;
    priorityId: PriorityId;
} {
    return {
        status: from_candid_TicketStatus_n17(_uploadFile, _downloadFile, value.status),
        title: value.title,
        isAtRisk: value.isAtRisk,
        slaDeadline: value.slaDeadline,
        isBreached: value.isBreached,
        timeRemainingNs: value.timeRemainingNs,
        ticketId: value.ticketId,
        priorityId: value.priorityId
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdOverTime: Array<[_Timestamp, bigint]>;
    totalTickets: bigint;
    byStatus: Array<[_TicketStatus, bigint]>;
    byCategory: Array<[_CategoryId, bigint]>;
    byPriority: Array<[_PriorityId, bigint]>;
}): {
    createdOverTime: Array<[Timestamp, bigint]>;
    totalTickets: bigint;
    byStatus: Array<[TicketStatus, bigint]>;
    byCategory: Array<[CategoryId, bigint]>;
    byPriority: Array<[PriorityId, bigint]>;
} {
    return {
        createdOverTime: value.createdOverTime,
        totalTickets: value.totalTickets,
        byStatus: from_candid_vec_n62(_uploadFile, _downloadFile, value.byStatus),
        byCategory: value.byCategory,
        byPriority: value.byPriority
    };
}
function from_candid_record_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AuditLogId;
    action: _AuditAction;
    actorId: _UserId;
    detail: string;
    timestamp: _Timestamp;
    targetEntity: string;
}): {
    id: AuditLogId;
    action: AuditAction;
    actorId: UserId;
    detail: string;
    timestamp: Timestamp;
    targetEntity: string;
} {
    return {
        id: value.id,
        action: from_candid_AuditAction_n81(_uploadFile, _downloadFile, value.action),
        actorId: value.actorId,
        detail: value.detail,
        timestamp: value.timestamp,
        targetEntity: value.targetEntity
    };
}
function from_candid_record_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    notificationType: _NotificationType;
    createdAt: _Timestamp;
    recipient: _UserId;
    isRead: boolean;
    message: string;
    linkTicketId: [] | [_TicketId];
}): {
    id: NotificationId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    recipient: UserId;
    isRead: boolean;
    message: string;
    linkTicketId?: TicketId;
} {
    return {
        id: value.id,
        notificationType: from_candid_NotificationType_n87(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt,
        recipient: value.recipient,
        isRead: value.isRead,
        message: value.message,
        linkTicketId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.linkTicketId))
    };
}
function from_candid_record_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    body: string;
    createdAt: _Timestamp;
    authorRole: _AppRole;
    ticketId: _TicketId;
    author: _UserId;
    isInternal: boolean;
}): {
    id: MessageId;
    body: string;
    createdAt: Timestamp;
    authorRole: AppRole;
    ticketId: TicketId;
    author: UserId;
    isInternal: boolean;
} {
    return {
        id: value.id,
        body: value.body,
        createdAt: value.createdAt,
        authorRole: from_candid_AppRole_n12(_uploadFile, _downloadFile, value.authorRole),
        ticketId: value.ticketId,
        author: value.author,
        isInternal: value.isInternal
    };
}
function from_candid_tuple_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_TicketStatus, bigint]): [TicketStatus, bigint] {
    return [
        from_candid_TicketStatus_n17(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    l2_resolver: null;
} | {
    l1_help_desk: null;
} | {
    employee: null;
}): AppRole {
    return "admin" in value ? AppRole.admin : "l2_resolver" in value ? AppRole.l2_resolver : "l1_help_desk" in value ? AppRole.l1_help_desk : "employee" in value ? AppRole.employee : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    closed: null;
} | {
    pending: null;
} | {
    in_progress: null;
} | {
    open: null;
}): TicketStatus {
    return "resolved" in value ? TicketStatus.resolved : "closed" in value ? TicketStatus.closed : "pending" in value ? TicketStatus.pending : "in_progress" in value ? TicketStatus.in_progress : "open" in value ? TicketStatus.open : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    l1: null;
} | {
    l2: null;
}): ResolverTier {
    return "l1" in value ? ResolverTier.l1 : "l2" in value ? ResolverTier.l2 : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    l1Default: null;
} | {
    l2Default: null;
}): ResolverQueue {
    return "l1Default" in value ? ResolverQueue.l1Default : "l2Default" in value ? ResolverQueue.l2Default : value;
}
function from_candid_variant_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    priorityUpdated: null;
} | {
    ticketAssigned: null;
} | {
    userDeactivated: null;
} | {
    categoryUpdated: null;
} | {
    userReactivated: null;
} | {
    settingsUpdated: null;
} | {
    ticketStatusChanged: null;
} | {
    ticketCreated: null;
} | {
    ticketClosed: null;
} | {
    roleChanged: null;
} | {
    categoryCreated: null;
}): AuditAction {
    return "priorityUpdated" in value ? AuditAction.priorityUpdated : "ticketAssigned" in value ? AuditAction.ticketAssigned : "userDeactivated" in value ? AuditAction.userDeactivated : "categoryUpdated" in value ? AuditAction.categoryUpdated : "userReactivated" in value ? AuditAction.userReactivated : "settingsUpdated" in value ? AuditAction.settingsUpdated : "ticketStatusChanged" in value ? AuditAction.ticketStatusChanged : "ticketCreated" in value ? AuditAction.ticketCreated : "ticketClosed" in value ? AuditAction.ticketClosed : "roleChanged" in value ? AuditAction.roleChanged : "categoryCreated" in value ? AuditAction.categoryCreated : value;
}
function from_candid_variant_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ticketReply: null;
} | {
    ticketUpdated: null;
} | {
    ticketAssigned: null;
} | {
    ticketClosed: null;
} | {
    roleChanged: null;
}): NotificationType {
    return "ticketReply" in value ? NotificationType.ticketReply : "ticketUpdated" in value ? NotificationType.ticketUpdated : "ticketAssigned" in value ? NotificationType.ticketAssigned : "ticketClosed" in value ? NotificationType.ticketClosed : "roleChanged" in value ? NotificationType.roleChanged : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TicketView>): Array<TicketView> {
    return value.map((x)=>from_candid_TicketView_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NavItem>): Array<NavItem> {
    return value.map((x)=>from_candid_NavItem_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TicketSLAStatus>): Array<TicketSLAStatus> {
    return value.map((x)=>from_candid_TicketSLAStatus_n57(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_TicketStatus, bigint]>): Array<[TicketStatus, bigint]> {
    return value.map((x)=>from_candid_tuple_n63(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditLogView>): Array<AuditLogView> {
    return value.map((x)=>from_candid_AuditLogView_n79(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KnowledgeArticleView>): Array<KnowledgeArticleView> {
    return value.map((x)=>from_candid_KnowledgeArticleView_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationView>): Array<NotificationView> {
    return value.map((x)=>from_candid_NotificationView_n85(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TicketMessage>): Array<TicketMessage> {
    return value.map((x)=>from_candid_TicketMessage_n90(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserView>): Array<UserView> {
    return value.map((x)=>from_candid_UserView_n9(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_AuditAction_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuditAction): _AuditAction {
    return to_candid_variant_n77(_uploadFile, _downloadFile, value);
}
function to_candid_AuditLogQuery_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuditLogQuery): _AuditLogQuery {
    return to_candid_record_n75(_uploadFile, _downloadFile, value);
}
function to_candid_CategoryUpdateInput_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CategoryUpdateInput): _CategoryUpdateInput {
    return to_candid_record_n96(_uploadFile, _downloadFile, value);
}
function to_candid_KnowledgeArticleCreateInput_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KnowledgeArticleCreateInput): _KnowledgeArticleCreateInput {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_KnowledgeArticleUpdateInput_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KnowledgeArticleUpdateInput): _KnowledgeArticleUpdateInput {
    return to_candid_record_n98(_uploadFile, _downloadFile, value);
}
function to_candid_PriorityUpdateInput_n100(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriorityUpdateInput): _PriorityUpdateInput {
    return to_candid_record_n101(_uploadFile, _downloadFile, value);
}
function to_candid_ResolverTier_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResolverTier): _ResolverTier {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function to_candid_SortOrder_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): _SortOrder {
    return to_candid_variant_n73(_uploadFile, _downloadFile, value);
}
function to_candid_SystemSettingsUpdateInput_n102(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SystemSettingsUpdateInput): _SystemSettingsUpdateInput {
    return to_candid_record_n103(_uploadFile, _downloadFile, value);
}
function to_candid_TicketQuery_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketQuery): _TicketQuery {
    return to_candid_record_n68(_uploadFile, _downloadFile, value);
}
function to_candid_TicketStatus_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketStatus): _TicketStatus {
    return to_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function to_candid_TicketUpdateInput_n104(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketUpdateInput): _TicketUpdateInput {
    return to_candid_record_n105(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResolverTier | null): [] | [_ResolverTier] {
    return value === null ? candid_none() : candid_some(to_candid_ResolverTier_n65(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole | null): [] | [_AppRole] {
    return value === null ? candid_none() : candid_some(to_candid_AppRole_n7(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CategoryId | null): [] | [_CategoryId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n101(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: PriorityId;
    name?: string;
    isActive?: boolean;
    level?: bigint;
    slaTargetNs?: bigint;
}): {
    id: _PriorityId;
    name: [] | [string];
    isActive: [] | [boolean];
    level: [] | [bigint];
    slaTargetNs: [] | [bigint];
} {
    return {
        id: value.id,
        name: value.name ? candid_some(value.name) : candid_none(),
        isActive: value.isActive ? candid_some(value.isActive) : candid_none(),
        level: value.level ? candid_some(value.level) : candid_none(),
        slaTargetNs: value.slaTargetNs ? candid_some(value.slaTargetNs) : candid_none()
    };
}
function to_candid_record_n103(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organizationName?: string;
    aiFeaturesEnabled?: boolean;
}): {
    organizationName: [] | [string];
    aiFeaturesEnabled: [] | [boolean];
} {
    return {
        organizationName: value.organizationName ? candid_some(value.organizationName) : candid_none(),
        aiFeaturesEnabled: value.aiFeaturesEnabled ? candid_some(value.aiFeaturesEnabled) : candid_none()
    };
}
function to_candid_record_n105(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: TicketStatus;
    assignedAgent?: UserId;
    resolutionSummary?: string;
    ticketId: TicketId;
}): {
    status: [] | [_TicketStatus];
    assignedAgent: [] | [_UserId];
    resolutionSummary: [] | [string];
    ticketId: _TicketId;
} {
    return {
        status: value.status ? candid_some(to_candid_TicketStatus_n69(_uploadFile, _downloadFile, value.status)) : candid_none(),
        assignedAgent: value.assignedAgent ? candid_some(value.assignedAgent) : candid_none(),
        resolutionSummary: value.resolutionSummary ? candid_some(value.resolutionSummary) : candid_none(),
        ticketId: value.ticketId
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryId?: CategoryId;
    title: string;
    content: string;
}): {
    categoryId: [] | [_CategoryId];
    title: string;
    content: string;
} {
    return {
        categoryId: value.categoryId ? candid_some(value.categoryId) : candid_none(),
        title: value.title,
        content: value.content
    };
}
function to_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryId?: CategoryId;
    status?: TicketStatus;
    creator?: UserId;
    sortBy?: Variant_createdAt_updatedAt_priority;
    sortOrder?: SortOrder;
    assignedAgent?: UserId;
    page: PageRequest;
    search?: string;
    priorityId?: PriorityId;
}): {
    categoryId: [] | [_CategoryId];
    status: [] | [_TicketStatus];
    creator: [] | [_UserId];
    sortBy: [] | [{
            createdAt: null;
        } | {
            updatedAt: null;
        } | {
            priority: null;
        }];
    sortOrder: [] | [_SortOrder];
    assignedAgent: [] | [_UserId];
    page: _PageRequest;
    search: [] | [string];
    priorityId: [] | [_PriorityId];
} {
    return {
        categoryId: value.categoryId ? candid_some(value.categoryId) : candid_none(),
        status: value.status ? candid_some(to_candid_TicketStatus_n69(_uploadFile, _downloadFile, value.status)) : candid_none(),
        creator: value.creator ? candid_some(value.creator) : candid_none(),
        sortBy: value.sortBy ? candid_some(to_candid_variant_n71(_uploadFile, _downloadFile, value.sortBy)) : candid_none(),
        sortOrder: value.sortOrder ? candid_some(to_candid_SortOrder_n72(_uploadFile, _downloadFile, value.sortOrder)) : candid_none(),
        assignedAgent: value.assignedAgent ? candid_some(value.assignedAgent) : candid_none(),
        page: value.page,
        search: value.search ? candid_some(value.search) : candid_none(),
        priorityId: value.priorityId ? candid_some(value.priorityId) : candid_none()
    };
}
function to_candid_record_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    toTimestamp?: Timestamp;
    action?: AuditAction;
    fromTimestamp?: Timestamp;
    page: PageRequest;
    actorId?: UserId;
}): {
    toTimestamp: [] | [_Timestamp];
    action: [] | [_AuditAction];
    fromTimestamp: [] | [_Timestamp];
    page: _PageRequest;
    actorId: [] | [_UserId];
} {
    return {
        toTimestamp: value.toTimestamp ? candid_some(value.toTimestamp) : candid_none(),
        action: value.action ? candid_some(to_candid_AuditAction_n76(_uploadFile, _downloadFile, value.action)) : candid_none(),
        fromTimestamp: value.fromTimestamp ? candid_some(value.fromTimestamp) : candid_none(),
        page: value.page,
        actorId: value.actorId ? candid_some(value.actorId) : candid_none()
    };
}
function to_candid_record_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: CategoryId;
    name?: string;
    description?: string;
    isActive?: boolean;
}): {
    id: _CategoryId;
    name: [] | [string];
    description: [] | [string];
    isActive: [] | [boolean];
} {
    return {
        id: value.id,
        name: value.name ? candid_some(value.name) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        isActive: value.isActive ? candid_some(value.isActive) : candid_none()
    };
}
function to_candid_record_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: KnowledgeArticleId;
    categoryId?: CategoryId | null;
    title?: string;
    content?: string;
}): {
    id: _KnowledgeArticleId;
    categoryId: [] | [[] | [_CategoryId]];
    title: [] | [string];
    content: [] | [string];
} {
    return {
        id: value.id,
        categoryId: value.categoryId ? candid_some(to_candid_opt_n99(_uploadFile, _downloadFile, value.categoryId)) : candid_none(),
        title: value.title ? candid_some(value.title) : candid_none(),
        content: value.content ? candid_some(value.content) : candid_none()
    };
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResolverTier): {
    l1: null;
} | {
    l2: null;
} {
    return value == ResolverTier.l1 ? {
        l1: null
    } : value == ResolverTier.l2 ? {
        l2: null
    } : value;
}
function to_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketStatus): {
    resolved: null;
} | {
    closed: null;
} | {
    pending: null;
} | {
    in_progress: null;
} | {
    open: null;
} {
    return value == TicketStatus.resolved ? {
        resolved: null
    } : value == TicketStatus.closed ? {
        closed: null
    } : value == TicketStatus.pending ? {
        pending: null
    } : value == TicketStatus.in_progress ? {
        in_progress: null
    } : value == TicketStatus.open ? {
        open: null
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_createdAt_updatedAt_priority): {
    createdAt: null;
} | {
    updatedAt: null;
} | {
    priority: null;
} {
    return value == Variant_createdAt_updatedAt_priority.createdAt ? {
        createdAt: null
    } : value == Variant_createdAt_updatedAt_priority.updatedAt ? {
        updatedAt: null
    } : value == Variant_createdAt_updatedAt_priority.priority ? {
        priority: null
    } : value;
}
function to_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): {
    asc: null;
} | {
    desc: null;
} {
    return value == SortOrder.asc ? {
        asc: null
    } : value == SortOrder.desc ? {
        desc: null
    } : value;
}
function to_candid_variant_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuditAction): {
    priorityUpdated: null;
} | {
    ticketAssigned: null;
} | {
    userDeactivated: null;
} | {
    categoryUpdated: null;
} | {
    userReactivated: null;
} | {
    settingsUpdated: null;
} | {
    ticketStatusChanged: null;
} | {
    ticketCreated: null;
} | {
    ticketClosed: null;
} | {
    roleChanged: null;
} | {
    categoryCreated: null;
} {
    return value == AuditAction.priorityUpdated ? {
        priorityUpdated: null
    } : value == AuditAction.ticketAssigned ? {
        ticketAssigned: null
    } : value == AuditAction.userDeactivated ? {
        userDeactivated: null
    } : value == AuditAction.categoryUpdated ? {
        categoryUpdated: null
    } : value == AuditAction.userReactivated ? {
        userReactivated: null
    } : value == AuditAction.settingsUpdated ? {
        settingsUpdated: null
    } : value == AuditAction.ticketStatusChanged ? {
        ticketStatusChanged: null
    } : value == AuditAction.ticketCreated ? {
        ticketCreated: null
    } : value == AuditAction.ticketClosed ? {
        ticketClosed: null
    } : value == AuditAction.roleChanged ? {
        roleChanged: null
    } : value == AuditAction.categoryCreated ? {
        categoryCreated: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    admin: null;
} | {
    l2_resolver: null;
} | {
    l1_help_desk: null;
} | {
    employee: null;
} {
    return value == AppRole.admin ? {
        admin: null
    } : value == AppRole.l2_resolver ? {
        l2_resolver: null
    } : value == AppRole.l1_help_desk ? {
        l1_help_desk: null
    } : value == AppRole.employee ? {
        employee: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
